= Gradle Bulk Artifact Publisher

This is a quick and dirty Gradle project for publishing a large collection of existing artifacts into a target
repository.  I had access to the folder structure of an existing repo containing all the artifacts and POM files
and I needed them published into another repository.

== How it works
You configure `project.ext.sourceFolder` in the build.gradle file to point to a folder containing the existing POM
files and artifacts and the project recursively searches the directory tree.  Because the search is recursive the target
folder can be the root of the repo or a folder of a specific artifact version.  For each POM file discovered, a
publication is configured using the Gradle `maven-publish` plugin.

You can then execute the publish using `gradle publish`

See source of `build.gradle` file for more info.

== Features
- Handles copying over extra POM information such as dependencies, developer info, etc.  This can be expanded by adding
  to the `extraNodeNames` array.  NOTE:  That this is done by modifying the generated POM file using the technique
  documented  https://docs.gradle.org/6.9.2/userguide/publishing_maven.html#sec:modifying_the_generated_pom[here].

== Limitations
- Only handles specific types of artifacts: (JARs, ZIPs, Source JARs and Grails plugin XML).  Others should be able to
  be added pretty easily by just following the implementation pattern.
